[build]
  command = "npm run build"
  publish = "dist"
  functions = "netlify/functions"

[dev]
  command = "npm run dev"
  port = 5173
  publish = "dist"
  targetPort = 5173

[build.environment]
  NODE_VERSION = "18"

# Handle SPA routing - all routes should redirect to index.html
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Cache settings
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"
    
    # Cache static assets for 1 year
    Cache-Control = "public, max-age=31536000, immutable"

# Don't cache HTML files
[[headers]]
  for = "/*.html"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"
